import type { FilterDataType, FilterOperatorDefinition } from "./types";

const comparable: FilterDataType[] = ["integer", "decimal", "date", "datetime", "time"];
const scalar: FilterDataType[] = [
  "string",
  "integer",
  "decimal",
  "boolean",
  "date",
  "datetime",
  "time",
  "unknown",
];

export const FILTER_OPERATORS: FilterOperatorDefinition[] = [
  {
    id: "equals",
    label: "es igual a",
    nodeType: "comparison",
    astOperator: "equals",
    compatibleTypes: "all",
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "not_equals",
    label: "es diferente de",
    nodeType: "comparison",
    astOperator: "not_equals",
    compatibleTypes: "all",
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "greater_than",
    label: "es mayor / posterior a",
    nodeType: "comparison",
    astOperator: "greater_than",
    compatibleTypes: comparable,
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "greater_than_or_equal",
    label: "es mayor o igual / desde",
    nodeType: "comparison",
    astOperator: "greater_than_or_equal",
    compatibleTypes: comparable,
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "less_than",
    label: "es menor / anterior a",
    nodeType: "comparison",
    astOperator: "less_than",
    compatibleTypes: comparable,
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "less_than_or_equal",
    label: "es menor o igual / hasta",
    nodeType: "comparison",
    astOperator: "less_than_or_equal",
    compatibleTypes: comparable,
    cardinality: "one",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "contains",
    label: "contiene",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
    likeAffix: "contains",
  },
  {
    id: "not_contains",
    label: "no contiene",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
    negated: true,
    likeAffix: "contains",
  },
  {
    id: "starts_with",
    label: "empieza con",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
    likeAffix: "starts",
  },
  {
    id: "ends_with",
    label: "termina con",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
    likeAffix: "ends",
  },
  {
    id: "like",
    label: "coincide con LIKE",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
  },
  {
    id: "not_like",
    label: "no coincide con LIKE",
    nodeType: "like",
    compatibleTypes: ["string"],
    cardinality: "one",
    valueSources: ["literal", "parameter"],
    negated: true,
  },
  {
    id: "between",
    label: "está entre",
    nodeType: "between",
    compatibleTypes: comparable,
    cardinality: "two",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "not_between",
    label: "no está entre",
    nodeType: "between",
    compatibleTypes: comparable,
    cardinality: "two",
    valueSources: ["literal", "parameter", "field"],
    negated: true,
  },
  {
    id: "in",
    label: "está en",
    nodeType: "in",
    compatibleTypes: scalar,
    cardinality: "many",
    valueSources: ["literal", "parameter", "field"],
  },
  {
    id: "not_in",
    label: "no está en",
    nodeType: "in",
    compatibleTypes: scalar,
    cardinality: "many",
    valueSources: ["literal", "parameter", "field"],
    negated: true,
  },
  {
    id: "is_null",
    label: "es NULL",
    nodeType: "is_null",
    compatibleTypes: "all",
    cardinality: "none",
    valueSources: [],
  },
  {
    id: "is_not_null",
    label: "no es NULL",
    nodeType: "is_null",
    compatibleTypes: "all",
    cardinality: "none",
    valueSources: [],
    negated: true,
  },
];

export const operatorsForType = (type: FilterDataType) =>
  FILTER_OPERATORS.filter(
    (operator) => operator.compatibleTypes === "all" || operator.compatibleTypes.includes(type),
  );

export const getFilterOperator = (id: string) => FILTER_OPERATORS.find((item) => item.id === id);
