import type { CompilationHistoryItem, CompilationResult, CompilerCapabilities, Complexity, QueryDocument, SavedQuery, SavedQueryList, ValidationResult } from "../features/queries/types";
import { apiRequest } from "./shared";

export const getQueryModelSchema = () => apiRequest<Record<string, unknown>>("/query-model/schema");
export const validateQueryModel = (document: QueryDocument) => apiRequest<ValidationResult>("/query-model/validate", { method: "POST", body: JSON.stringify(document) });
export const normalizeQueryModel = (document: QueryDocument) => apiRequest<{ normalized_query: QueryDocument; fingerprint: string }>("/query-model/normalize", { method: "POST", body: JSON.stringify(document) });
export const calculateQueryComplexity = (document: QueryDocument) => apiRequest<Complexity>("/query-model/complexity", { method: "POST", body: JSON.stringify(document) });
export const listQueries = () => apiRequest<SavedQueryList>("/queries");
export const createQuery = (payload: { name: string; description: string | null; document: QueryDocument }) => apiRequest<SavedQuery>("/queries", { method: "POST", body: JSON.stringify(payload) });
export const getQuery = (id: string) => apiRequest<SavedQuery>(`/queries/${id}`);
export const updateQuery = (id: string, payload: { revision: number; name?: string; description?: string | null; document?: QueryDocument }) => apiRequest<SavedQuery>(`/queries/${id}`, { method: "PATCH", body: JSON.stringify(payload) });
export const deleteQuery = (id: string) => apiRequest<undefined>(`/queries/${id}`, { method: "DELETE" });
export const archiveQuery = (id: string) => apiRequest<SavedQuery>(`/queries/${id}/archive`, { method: "POST" });
export const duplicateQuery = (id: string) => apiRequest<SavedQuery>(`/queries/${id}/duplicate`, { method: "POST" });
export const validateSavedQuery = (id: string) => apiRequest<ValidationResult>(`/queries/${id}/validate`, { method: "POST" });
export const compileUniversalQuery = (document: QueryDocument) => apiRequest<CompilationResult>("/query-compiler/compile", { method: "POST", body: JSON.stringify({ document, mode: "definition", preview_values: {} }) });
export const compileSavedQuery = (id: string) => apiRequest<CompilationResult>(`/queries/${id}/compile`, { method: "POST" });
export const getCompilerCapabilities = (connectionId: string) => apiRequest<CompilerCapabilities>(`/query-compiler/capabilities/${connectionId}`);
export const listQueryCompilations = (id: string) => apiRequest<{ items: CompilationHistoryItem[] }>(`/queries/${id}/compilations`);
export const getQueryCompilation = (queryId: string, compilationId: string) => apiRequest<CompilationResult>(`/queries/${queryId}/compilations/${compilationId}`);
