import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, CheckCircle2, Code2, Copy, FileJson2, Plus, Trash2 } from "lucide-react";
import { Link } from "react-router";

import { PageContainer } from "../components/layout/PageContainer";
import { PageHeader } from "../components/layout/PageHeader";
import { StatusBadge } from "../components/ui/StatusBadge";
import { useAuth } from "../features/auth/context";
import { archiveQuery, deleteQuery, duplicateQuery, listQueries, validateSavedQuery } from "../services/queries";

export function QueriesPage() {
  const client = useQueryClient();
  const { hasPermission } = useAuth();
  const query = useQuery({ queryKey: ["queries"], queryFn: listQueries });
  const mutate = useMutation({ mutationFn: async ({ id, action }: { id: string; action: string }) => { if (action === "validate") await validateSavedQuery(id); else if (action === "duplicate") await duplicateQuery(id); else if (action === "archive") await archiveQuery(id); else await deleteQuery(id); }, onSuccess: () => { void client.invalidateQueries({ queryKey: ["queries"] }); } });
  return <PageContainer><PageHeader eyebrow="Modelo universal" title="Consultas" description="Borradores técnicos representados como AST JSON; no contienen ni generan SQL." actions={<Link className="btn-primary" to="/queries/new"><Plus className="size-4" />Nueva consulta</Link>} />
    {query.isPending ? <p className="state-message">Cargando consultas…</p> : query.isError ? <p className="alert-error">No fue posible cargar los borradores.</p> : query.data.items.length === 0 ? <section className="rounded-xl border border-dashed bg-white p-12 text-center"><FileJson2 className="mx-auto size-10 text-blue-600" /><h2 className="mt-4 text-lg font-semibold">Aún no hay borradores</h2><p className="mt-1 text-sm text-slate-500">Crea una definición universal sin escribir SQL.</p></section> : <div className="grid gap-4">{query.data.items.map((item) => <article className="rounded-xl border bg-white p-5 shadow-sm" key={item.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Link className="font-semibold text-slate-900 hover:text-blue-700" to={`/queries/${item.id}`}>{item.name}</Link><StatusBadge variant={item.validation_status === "valid" ? "success" : item.validation_status === "invalid" ? "warning" : "neutral"}>{item.validation_status}</StatusBadge></div><p className="mt-1 text-sm text-slate-500">{item.description || "Sin descripción"}</p><p className="mt-2 text-xs text-slate-400">Revisión {item.revision} · {new Date(item.updated_at).toLocaleString()} · Complejidad {item.complexity?.level ?? "sin calcular"}</p></div><div className="flex gap-2"><Link aria-label="Editar JSON" className="btn-secondary" title="Editar JSON" to={`/queries/${item.id}/edit-json`}><FileJson2 className="size-4" /></Link>{hasPermission("queries.compile") && item.validation_status === "valid" ? <Link aria-label="Compilar" className="btn-secondary" title="Compilar" to={`/queries/${item.id}/compile`}><Code2 className="size-4" /></Link> : null}<button aria-label="Validar" className="btn-secondary" title="Validar" onClick={() => { mutate.mutate({ id: item.id, action: "validate" }); }}><CheckCircle2 className="size-4" /></button><button aria-label="Duplicar" className="btn-secondary" title="Duplicar" onClick={() => { mutate.mutate({ id: item.id, action: "duplicate" }); }}><Copy className="size-4" /></button><button aria-label="Archivar" className="btn-secondary" title="Archivar" onClick={() => { mutate.mutate({ id: item.id, action: "archive" }); }}><Archive className="size-4" /></button><button aria-label="Eliminar" className="btn-danger" title="Eliminar" onClick={() => { if (window.confirm("¿Eliminar este borrador?")) mutate.mutate({ id: item.id, action: "delete" }); }}><Trash2 className="size-4" /></button></div></div></article>)}</div>}
  </PageContainer>;
}
