import { Archive, Eye, FilePlus2, Trash2 } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Link } from "react-router";

import { PageContainer } from "../components/layout/PageContainer";
import { PageHeader } from "../components/layout/PageHeader";
import { StatusBadge } from "../components/ui/StatusBadge";
import { archiveReport, deleteReport, listReports, publishReport } from "../services/reports";

export function ReportsPage() {
  const client = useQueryClient(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("");
  const reports = useQuery({ queryKey: ["reports", search, status], queryFn: () => listReports(search, status) });
  const action = useMutation({ mutationFn: async ({ id, name }: { id: string; name: "publish" | "archive" | "delete" }) => { if (name === "publish") return publishReport(id); if (name === "archive") return archiveReport(id); await deleteReport(id); return undefined; }, onSuccess: async () => client.invalidateQueries({ queryKey: ["reports"] }) });
  return <PageContainer><PageHeader eyebrow="Reportes reutilizables" title="Reportes" description="Presenta y exporta consultas guardadas sin ejecutar SQL libre." actions={<Link className="btn-primary" to="/reports/new"><FilePlus2 className="size-4" />Crear reporte</Link>} /><div className="flex gap-3 rounded-xl border bg-white p-3"><input aria-label="Buscar reportes" className="field max-w-sm" placeholder="Buscar reportes…" value={search} onChange={(event) => { setSearch(event.target.value); }} /><select aria-label="Filtrar estado" className="field max-w-48" value={status} onChange={(event) => { setStatus(event.target.value); }}><option value="">Activos</option><option value="draft">Borradores</option><option value="published">Publicados</option><option value="archived">Archivados</option></select></div>{reports.isPending ? <p className="state-message">Cargando reportes…</p> : reports.isError ? <p className="alert-error">No fue posible cargar los reportes.</p> : <section className="overflow-hidden rounded-xl border bg-white">{reports.data.items.map((report) => <article className="grid gap-3 border-b p-5 lg:grid-cols-[1fr_auto] lg:items-center" key={report.id}><div><div className="flex gap-2"><strong>{report.name}</strong><StatusBadge variant={report.status === "published" ? "success" : "info"}>{report.status}</StatusBadge></div><p className="mt-1 text-sm text-slate-500">{report.description || report.title}</p><p className="mt-1 text-xs text-slate-400">Consulta {report.query_id.slice(0, 8)} · revisión {report.query_revision} · {new Date(report.updated_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Link className="btn-secondary" to={`/reports/${report.id}`}><Eye className="size-4" />Abrir</Link><Link className="btn-secondary" to={`/reports/${report.id}/edit`}>Editar</Link>{report.status === "draft" ? <button className="btn-primary" onClick={() => { action.mutate({ id: report.id, name: "publish" }); }}>Publicar</button> : null}{report.status !== "archived" ? <button className="icon-button" aria-label="Archivar" onClick={() => { if (confirm("¿Archivar este reporte?")) action.mutate({ id: report.id, name: "archive" }); }}><Archive className="size-4" /></button> : null}<button className="icon-button text-red-600" aria-label="Eliminar" onClick={() => { if (confirm("¿Eliminar el reporte y sus archivos?")) action.mutate({ id: report.id, name: "delete" }); }}><Trash2 className="size-4" /></button></div></article>)}{reports.data.items.length === 0 ? <p className="state-message">Aún no hay reportes.</p> : null}</section>}</PageContainer>;
}
